# Đề thi mẫu chứng chỉ TensorFlow - Dạng bài 01

```
ProtonX - TensorFlow Class
```
Giới thiệu về chứng chỉ - https://www.tensorflow.org/certificate

> Chú ý: đọc kỹ các nội dung trong Handle Notebook trong liên kết trên.

---

### Hướng dẫn làm bài

Đọc kỹ File `Tensorflow Exam - Tips` trên hệ thống Google.

*Một số yêu cầu:
- Sử dụng TensorFlow 2.x trở lên.
- Không có tập validation nên train tầm 500 - 1000 epochs để đảm bảo đạt độ chính xác.
- Chạy lại toàn bộ File này trước khi ấn nộp bài.

### Phần lập trình

In [1]:
# Import thư viện cần thiết
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential

In [2]:
# Dữ liệu
xs = [2, 7, 9, 3, 10, 6, 1, 8]
ys = [13, 35, 41, 19, 45, 28, 10, 55]


In [3]:
xs = np.array(xs, dtype = float)
ys = np.array(ys, dtype = float)

min_feature, max_feature = min(xs), max(xs)
feature = (xs - min_feature) / (max_feature - min_feature)

In [4]:
xs

array([ 2.,  7.,  9.,  3., 10.,  6.,  1.,  8.])

In [5]:
feature

array([0.11111111, 0.66666667, 0.88888889, 0.22222222, 1.        ,
       0.55555556, 0.        , 0.77777778])

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, input_shape = [1])
])

In [7]:
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')

In [8]:
model.fit(xs, ys, epochs = 750, verbose = 1)

Epoch 1/750
1/1 [==============================] - 0s 337ms/step - loss: 1145.3479
Epoch 2/750
1/1 [==============================] - 0s 10ms/step - loss: 54.8291
Epoch 3/750
1/1 [==============================] - 0s 10ms/step - loss: 37.8691
Epoch 4/750
1/1 [==============================] - 0s 10ms/step - loss: 37.5608
Epoch 5/750
1/1 [==============================] - 0s 10ms/step - loss: 37.5111
Epoch 6/750
1/1 [==============================] - 0s 11ms/step - loss: 37.4659
Epoch 7/750
1/1 [==============================] - 0s 14ms/step - loss: 37.4212
Epoch 8/750
1/1 [==============================] - 0s 10ms/step - loss: 37.3768
Epoch 9/750
1/1 [==============================] - 0s 11ms/step - loss: 37.3329
Epoch 10/750
1/1 [==============================] - 0s 10ms/step - loss: 37.2893
Epoch 11/750
1/1 [==============================] - 0s 9ms/step - loss: 37.2462
Epoch 12/750
1/1 [==============================] - 0s 11ms/step - loss: 37.2034
Epoch 13/750
1/1 [=================

In [9]:
# Lưu Model và nộp
model.save("mymodel.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [15]:
model.predict([3])

1/1 [==============================] - 0s 39ms/step


array([[18.532835]], dtype=float32)